# Docker compose to postgresql on finance-go

version: '3.1'

services:
  postgres:
    image: postgres:12
    container_name: finance-go-postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: finance-go
      POSTGRES_PASSWORD: finance-go
      POSTGRES_DB: finance-go
    volumes:
      - ./data:/var/lib/postgresql/data
